# Generated by Django 5.2.4 on 2025-07-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='myapp.task')),
            ],
            options={
                'verbose_name': 'Task Status Change',
                'verbose_name_plural': 'Task Status Changes',
                'db_table': 'task_manager_task_status_change',
            },
        ),
    ]
